name: Gitconvex React UI build pipeline for collaborators

on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 13.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm uninstall tailwindcss postcss autoprefixer
      - run: npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
      - run: npm uninstall tailwindcss @tailwindcss/postcss7-compat
      - run: npm i -g create-react-app tailwindcss@latest postcss@latest autoprefixer@latest
      - run: npm run build:tailwind
      - run: npm test && npm run build
